# <font color='blue'> COMANDOS BÁSICOS DE PYTHON </font>

<i>Autor: Silvio da Rosa Paula </i>               
<i>Data: 27/07/2021 </i>

**---------------------------------------------------------------------------**
##  MÓDULO 1 - Pacotes e Configurações

**Para abrir o Jupyter notebook direto da pasta onde estão os scripts** 

* Pressione shift + Botão direto do mouse / seleciona abrir janela do powershel aqui / digite: jupyter notebook 

**LINKS ÚTEIS**     

* Documentação Python https://docs.python.org/release/3.6.4/

* PyPi https://pypi.python.org/pypiData 

**Para instalar thema escuro no jupyter via pronpt de comando do python**
* pip install jupyterthemes      
* jt -l # para listar themas      
* jt -t monokai # escolhendo thema monokai      
* jt -r # thema padrão      

**Uma extensão do chorme boa para deixar o tema escuro é Dark Reader**     
* https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=pt-BR

In [ ]:
# Observações importantes
# No python tudo começa em zero
# O Python é case-sensitive.

In [ ]:
# Instalar vizualizador de variáveis no jupyter lab (instalar via cmd)
!pip3 install lckr-jupyterlab-variableinspector

In [ ]:
# Ver a versão do Python que estamos utilizando
from platform import python_version
print('Versão da Linguagem Python', python_version())

In [6]:
# Para inserir comentários maiores ou texto
"""cole o texto aqui"""

'cole o texto aqui'

In [ ]:
# Para instalar um pacote diretamente do notebook
!pip3 install pandas
!pip3 install matplotlib
!pip3 install seaborn
!pip3 install numpy

In [ ]:
# Instalar uma versão especifica de um pacote
!pip install -q -U matplotlib==3.2.1

In [ ]:
# Instala o pacote de modo silencioso, ou seja, não mostra nada exceto se der erro "-q"
!pip install -q imdb-sqlite

In [ ]:
# Imprimir um Jupyter notebook para pdf 
# OBS: (instalar diretamente no prompt do python)
pip install -U notebook-as-pdf
pyppeteer-install

In [ ]:
# Se quiser somente converter um Jupyter notebook direto para pdf basta usar
jupyter-nbconvert --to PDFviaHTML example.ipynb

In [ ]:
# Para atualizar um pacote
!pip install numpy -U

In [ ]:
# Ver versão de um pacote 
np.__version__

In [24]:
# importar pacotes instalados
#[OBS: o comando significa "importar pandas como pd" então basta chamar pd ao invés de pandas]
import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns

In [ ]:
# Importar todos os módulos do NumPy, isso evitará a utilização de np.
from numpy import * . 

In [ ]:
# importar somente um modulo de um pacote
import matplotlib.pyplot as plt
from sklearn.utils import resample

In [ ]:
# ver versão de um pacote
import pandas as pd
pd.__version__

In [ ]:
# Ver todos os modulos de um pacote 
dir(pd)

In [ ]:
# Ver pasta de trabalho
%pwd

In [ ]:
# Alterar pasta de trabalho
%cd C:\...

In [ ]:
# Para acessar o help de um pacote 
help(pd)

In [ ]:
# Filtar warnings
#import warnings 

In [ ]:
# Adicionar uma imagen do pc no jupyter notebook
from IPython.display import Image
Image(filename='Imagens_utilizadas/imagem_python.jpg',width=600, height=300)

In [ ]:
# Adicionar uma imagem da web no jupyter notebook
from IPython.core.display import HTML 
Image(url= "https://www.cetax.com.br/blog/wp-content/uploads/2017/10/Python-import-chamada-m%C3%A9todo-din%C3%A2mica.gif")

Para oculutar a URL atribuindo a uma palavra ou texto, como no word, <a
href="https://www.imdb.com/interfaces/">IMDB</a>.                 

### **-------------------------------------------------------------------------------------------**
##   MÓDULO 2 - Criar Objetos

###  STRINGS 

* As strings são sequências de caracteres, de forma que podemos acessar um caractere em uma dada posição utilizando um índice. 

* Para criar uma string em Python você pode usar aspas simples ou duplas.

In [ ]:
# Uma única palavra
"Oi"

# Uma frase
'Criando uma string em Python'

# Você pode combinar aspas duplas e simples
"Testando strings em 'Python'"

# Imprimir uma string
print ('Testando Strings em Python')

# Imprimir uma string com uma palavra abaixo da outra utilizando 
#o "enter do python" \n
print ('Testando \nStrings \nem \nPython')

# Atribuindo uma string
s = 'Data Science Academy'

# Primeiro elemento da string. 
s[0]

# Retorna todos os elementos da string, começando pela posição 
#(lembre-se que Python começa a indexação pela posição 0), até o fim da string.
s[1:]

# Retorna tudo até a posição 3
s[:3]

# Nós também podemos usar a indexação negativa e ler de trás para frente.
s[-1]

# Retornar tudo, exceto a última letra
s[:-1]

# Nós também podemos usar a notação de índice e fatiar a string em pedaços específicos (o padrão é 1). 
# Por exemplo, podemos usar dois pontos duas vezes em uma linha e, em seguida, um número que especifica 
# a frequência para retornar elementos. Por exemplo:
s[::1]

# Podemos usar o símbolo de multiplicação para criar repetição!
letra = 'w'
letra * 3

# Upper Case (deixar tudo maiusculo) 
s.upper()

# Upper Case (deixar tudo minusculo) 
s.upper()

# Dividir uma string por espaços em branco (padrão)
s.split()

# Dividir uma string por um elemento específico
s.split('y')

# Funções String
s = 'seja bem vindo ao universo de python'
s.capitalize() # deixar primeira letra maiuscula
s.count('a')   # contar o numero de letras a no texto
s.find('p')    # encontrar a posição da letra p

# Comparando Strings
print("Python" == "R")
print("Python" == "Python")

###  LISTAS 

* Uma lista (list) em Python é uma sequência ou coleção ordenada de valores. Cada valor na lista é identificado por um índice. O valores que formam uma lista são chamados elementos ou itens. Listas são similares a strings, que são uma sequência de caracteres, no entanto, diferentemente de strings, os itens de uma lista podem ser de tipos diferentes

* Para criar um dicionário se usa colchetes [ ]
* Listas de listas são matrizes em Python

In [16]:
# Criando uma lista
lista = [10, "farinha e leite", "maças"]

# Imprimindo a lista
print(lista)

# Verificando o comprimento de uma lista
len(lista)

# Slicing, de uma lista (pegar todos itens a partir da primeira posição)
lista[1:]

# Slicing, de uma lista (pegar todos antes da segunda posição)
lista[:2]

# Atribuindo cada valor da lista a uma variável.
item1 = lista[0]
item2 = lista[1]
item3 = lista[2]

# Imprimindo as variáveis
print(item1, item2, item3)

# Imprimindo um item da lista
lista[2]

# Atualizando um item da lista (replace lista)
lista[2] = "chocolate"
lista

# Deletando um item específico da lista
del lista[2]
lista

# Criando uma lista aninhada ou seja uma lista de listas
listas = [[1,2,3], [10,15,14], [10.1,8.7,2.3]]
listas

# Concatenando listas
lista_s1 = [34, 32, 56]
lista_s2 = [21, 90, 51]
lista_total = lista_s1 + lista_s2

# Verificando se o valor 10 pertence a lista (com operador IN)
print(21 in lista_total)

# Contar quantas vezes aparece um item em uma lista
lista.count("item")

# Adicionar um item a lita
lista.append(99)
lista

# Extendendo uma lista
cidades = ['Recife', 'Manaus', 'Salvador']
cidades.extend(['Fortaleza', 'Palmas'])
print (cidades)

# Remove um item da lista
cidades.remove("Recife")
cidades

# Reverte a lista
cidades.reverse()

# Deletando a tupla
# del lista

[10, 'farinha e leite', 'maças']
10 farinha e leite maças
True
['Recife', 'Manaus', 'Salvador', 'Fortaleza', 'Palmas']


###  TUPLA 

* Tupla é um tipo de estrutura de dados utilizada em Python que funciona de modo semelhante a uma lista, entretanto, com a característica principal de ser imutável. Isso significa que quando uma tupla é criada não é possível adicionar, alterar ou remover seus elementos. Geralmente, ela é utilizada para adicionar tipos diferentes de informações, porém, com a quantidade de elementos definidos.
* Para criar uma tupla se usa parenteses ()
* Tuplas não suportam atribuição de item
* Tuplas não suportam delete de um item específico
* Tuplas não suportam append()
* Tuplas podem ter um único item
* Para adiciar itens a uma tupla converta ela para lista e adicione itens e converta para lista

In [15]:
# Criando uma tupla
tupla1 = ["Geografia", 23, "Elefantes"]

# Imprimindo a tupla
tupla1

# Ver um unico item
tupla1[0]

# Verificando o comprimento da tupla
len(tupla1)

# Slicing, da mesma forma que se faz com listas
tupla1[1:]

# Usando a função list() para converter uma tupla para lista
lista_t2 = list(tupla1)

# Usando a função tuple() para converter uma lista para tupla
tupla1 = tuple(lista_t2)

# Deletando a tupla
del tupla1

### DICIONÁRIOS

* Dicionário é um tipo diferente de coleção. Ele é um tipo de mapeamento nativo do Python. Um mapa é uma coleção associativa desordenada. A associação, ou mapeamento, é feita a partir de uma chave, que pode ser qualquer tipo imutável, para um valor, que pode ser qualquer objeto de dados do Python.

* Para criar um dicionário se usa chave-valor. O dicionário vazio é denotado {}
* Os dicionarios são compostos por chave e valor, nesta ordem

In [17]:
# Criando um dicionario
estudantes = {"Mateus":24, "Fernanda":22, "Tamires":26, "Cristiano":25}

# Imprimindo um dicionario
estudantes

# Verificando o comprimento da tupla
len(estudantes_dict)

# Ver chaves de um dicionario ou seja 'Mateus', 'Fernanda', 'Tamires', 'Cristiano'
estudantes.keys()

# Ver valores de um dicionario
estudantes.values()

# Ver itens de uma dicionario
estudantes.items()

# Adicionar itens a uma dicionario
estudantes2 = {"Maria":27, "Erika":28, "Milton":26}
estudantes.update(estudantes2)
estudantes

# É possivel criar um dicionário de listas
dict3 = {'key1':1230,'key2':[22,453,73.4],'key3':['leite','maça','batata']}
dict3

# Criando dicionários aninhados
dict_aninhado = {'key1':{'key2_aninhada':{'key3_aninhada':'Dict aninhado em Python'}}}
dict_aninhado

# Deletando um dicionario
del dict_aninhado

NameError: name 'estudantes_dict' is not defined

### **------------------------------------------------------------------------------------------**
##   MÓDULO 3 - input, ifelse, for, while, metodos, funções, lambda 

##  Função input() 

* Serve para fazer abrir uma caixa de texto para imputar algo.

In [ ]:
disciplina = input('Digite o nome da disciplina que você quer cursar: ')
disciplina

In [18]:
# Usando a função int para converter o valor digitado
idade = int(input("Digite sua idade: "))
if idade > 13:
    print("Você pode acessar o Facebook")  

Digite sua idade:  12


## Funções IF, ELSE, ELIF

* O if é uma estrutura de condição que permite avaliar uma expressão e, de acordo com seu resultado, executar uma determinada ação.

* O encaderamento no Python é dado por um TAB ou 4 espaços
* if   -> se
* else -> caso contrario
* O elif serve para verificar outra condição caso a condição do If seja falsa.

In [19]:
# Condicional If
if 2 > 5:
    print("Esta correto!")
else:
    print("Esta errado!")
    
# Condicionar aninhados if else elif
dia = "Terça"
if dia == "Segunda":
    print("Hoje fará sol!")
elif dia == "Terça":
    print("Hoje vai chover!")
else:
    print("Sem previsão do tempo para o dia selecionado")

Esta errado!
Hoje vai chover!


In [ ]:
# Usando mais de uma condição na cláusula if e introduzindo Placeholders

disciplina = input('Digite o nome da disciplina: ')
nota_final = input('Digite a nota final (entre 0 e 100): ')
semestre = input('Digite o semestre (1 a 4): ')

if disciplina == 'Geografia' and nota_final >= '50' and int(semestre) != 1:
    print('Você foi aprovado em %s com média final %r!' %(disciplina, nota_final))
else:
    print('Lamento, acho que você precisa estudar mais!')

##  Função FOR( )

* A estrutura de repetição é um recurso das linguagens de programação responsável por executar um bloco de código repetidas vezes enquanto determinada condição é atendida.

* For -> tradução "para" 

In [ ]:
# Criando uma tupla e imprimindo cada um dos valores
tp = (2,3,4)
for i in tp:
    print(i)
    
# Criando uma lista e imprimindo cada um dos valores
ListaDoMercado = ["Leite", "Frutas", "Carne"]
for i in ListaDoMercado:
    print(i)

In [ ]:
# Função RANGE dentro do for
# Imprimindo os valores no intervalo entre 0 e 5 (exclusive)
for contador in range(0,5):
    print(contador)

In [20]:
# Imprimindo na tela os números pares da lista de números
lista = [1,2,3,4,5,6,7,8,9,10]
for num in lista:
    if num % 2 == 0: # obs: o operador % pede o resto da divisão
        print (num)

2
4
6
8
10


In [ ]:
# Listando os números no intervalo entre 0 e 10, com incremento em 2
for i in range(0,10,2):  
    print(i)

In [ ]:
# Strings também são sequências
for caracter in 'Python!':
    print (caracter)

In [ ]:
# Operando os valores de uma lista com loop for
listaB = [32,53,85,10,15,17,19]
soma = 0
for i in listaB:
    double_i = i * 2
    soma += double_i # o operador += vai somando conforme o loop vai rodando
print(soma)

In [21]:
# Contando o número de colunas
lst = [[1,2,3],[3,4,5],[5,6,7]]
primeira_linha = lst[0]
count = 0
for column in primeira_linha:
    count = count + 1
print(count)

3


In [ ]:
# Pesquisando em listas
listaC = [5, 6, 7, 10, 50]

# Loop através da lista
for item in listaC:
    if item == 50:
        print("Número encontrado na lista!")

##  Função WHILE( )

* A estrutura de repetição é um recurso das linguagens de programação responsável por executar um bloco de código repetidas vezes enquanto determinada condição é atendida.

* while -> tradução "enquanto" 


In [22]:
# Usando o loop while para imprimir os valores de 0 a 9
counter = 0
while counter <= 10:
    print(counter)
    counter = counter + 1

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
# Também é possível usar a claúsula else para encerrar o loop while
x = 0

while x < 10:
    print ('O valor de x nesta iteração é: ', x)
    print (' x ainda é menor que 10, somando 1 a x')
    x += 1
    
else:
    print ('Loop concluído!')

In [ ]:
counter = 0
while counter < 100:
    if counter == 4:
        break
    else:
        pass
    print(counter)
    counter = counter + 1

In [ ]:
for verificador in "Python":
    if verificador == "h":
        continue
    print(verificador)

## Função RANGE( )

* A função range () retorna uma sequência de números, começando em 0 por padrão e incrementando em 1 (por padrão), e pára antes de um número especificado.

In [ ]:
# Imprimindo números pares entre 50 e 101
for i in range(50, 70, 2):
    variavel = i
    print(variavel)
    
for i in range(3, 6):
    print (i)

In [ ]:
lista = ['Morango', 'Banana', 'Abacaxi', 'Uva']
lista_tamanho = len(lista)
for i in range(0, lista_tamanho):
    print(lista[i])

## Função DEF( )

* Podemos criar uma função qualquer do zero ou combinar funções em uma só.

In [ ]:
# Definindo uma função
def primeiraFunc():
    print('Hello World')
primeiraFunc()    

In [ ]:
# Função para somar números
def addNum(firstnum, secondnum):
    print("Primeiro número: " + str(firstnum))
    print("Segundo número: " + str(secondnum))
    print("Soma: ", firstnum + secondnum)
addNum(45, 3)

In [ ]:
import math
def numPrimo(num):
    '''
    Verificando se um número 
    é primo. 
    '''
    if (num % 2) == 0 and num > 2: 
        return "Este número não é primo"
    for i in range(3, int(math.sqrt(num)) + 1, 2):
        if (num % i) == 0:
            return "Este número não é primo"
    return "Este número é primo"

numPrimo(5) # quero saber se o numero 5 é primo

##  Função MAP( )

* Podemos usar a função integrada do Python, map(), para aplicar uma função a cada item em um iterável (como uma lista ou um dicionário) e retornar um novo iterador para recuperar os resultados. map() retorna um objeto map (um iterador), que podemos usar em outras partes do nosso programa. Também podemos passar o objeto map à função list(), ou outro tipo de sequência, para criar um iterável.

In [ ]:
# Criando duas funções

# Função 1 - Recebe uma temperatura como parâmetro e retorna a temperatura em Fahrenheit
def fahrenheit(T):
    return ((float(9)/5)*T + 32)

# Função 2 - Recebe uma temperatura como parâmetro e retorna a temperatura em Celsius
def celsius(T):
    return (float(5)/9)*(T-32)

# Criando uma lista
temperaturas = [0, 22.5, 40, 100]

# Função map() retornando a lista de temperaturas convertidas em Fahrenheit
list(map(fahrenheit, temperaturas))

In [ ]:
# Somando os elementos de 2 listas
a = [1,2,3,4]
b = [5,6,7,8]

list(map(lambda x,y:x+y, a, b))

## Função REDUCE( )

* A função reduce , disponível no módulo built-in functools , serve pra "reduzir" um iterável (como uma lista) a um único valor. É um paradigma um pouco mais comum em linguagens funcionais, mas que também é bastante útil em linguagens imperativas/orientadas a objetos como o Python.

In [ ]:
# Importando a função reduce do módulo functools
from functools import reduce

# Criando uma lista
lista = [47,11,42,13]

# Gerar uma funão de soma 
def soma(a,b):
    x = a + b
    return x

# Usando reduce com uma função e uma lista. A função vai retornar o valor máximo
reduce(soma, lista)

## Função FILTER( )

* A função Filter pega uma lista e aplica uma regra, onde compara cada elemento da lista contra a regra de filtragem booleana. Uma vez aplicada a condição, retorna um subconjunto da lista original.

In [ ]:
# Criando uma função para verificar se um numero é par
def verificaPar(num):
    if num % 2 == 0:
        return True
    else:
        return False

# lista de valores para verificar    
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

# Aplicando o filter
list(filter(verificaPar, lista))

## LIST COMPREHENSION

* Permite desenvolver listas usando uma notação diferente. Seria essencialmente uma linha de loop for, contruida dentro de [ ]
* Essa função é mais veloz que map ou filter pois roda em C.

In [ ]:
# Retornar cada caracter em uma sequência de caracteres
# Traduzindo esse comando: retornar x para cada x in uma sequencia.
lst = [x for x in 'python']

# Check
lst

# Variável x elevada ao quadrado para um range de números e retornar uma lista
lst = [x**2 for x in range(0, 11)]

# Check
lst

In [ ]:
# Converter Celsius para Fahrenheit
celsius = [0,10,20.1,34.5]

fahrenheit = [ ((float(9) / 5) * temp + 32) for temp in celsius ]

fahrenheit

##  Função ZIP( )

* A função zip agrega os valores de duas sequências e retorna uma tupla

In [ ]:
# Criando duas listas
x = [1,2,3]
y = [4,5,6]

# Perceba que zip retorna tuplas. Neste caso, uma lista de tuplas
list(zip(x,y))

In [ ]:
# Atenção quando as sequências tiverem número diferente de elementos alguns
# elementos firam de fora
a = [1,2,3]
b = [4,5,6,7,8]
list(zip(a,b)) 

In [ ]:
# Criando 2 dicionários
d1 = {'a':1,'b':2}
d2 = {'c':4,'d':5}

# Zip pode unir os valores (itens)
list(zip(d1, d2.values()))

## Função ENUMERATE( )

* A função enumerate permite retornar o índice de cada valor em uma sequência, á medida que você percorre toda a sequência. Gera tuplas.

In [ ]:
# Criando uma lista
seq = ['a','b','c']

list(enumerate(seq))

In [ ]:
# Imprimindo os valores de uma lista com a função enumerate() e seus índices
for indice, valor in enumerate(seq):
    print (indice, valor)

In [ ]:
# Imprimindo os valores de uma lista com a função enumerate() e seus índices
lista = ['Marketing', 'Tecnologia', 'Business']
for i, item in enumerate(lista):
    print(i, item)

## Variáveis GLOBAL e LOCAL

* Variável Global -> Em Python, uma variável declarada fora da função ou que seja de escopo global é conhecida como variável global. Isto significa que a variável global pode ser lida e atualizada dentro ou fora da função.

* Variável Local -> Toda variável declarada dentro do escopo de uma função ou método, é local a este método ou função. Ou seja, só é “reconhecida” por este trecho de código. Veja o exemplo a seguir:


In [ ]:
# Variável Global
var_global = 10  # Esta é uma variável global

def multiply(num1, num2):
    var_local = num1 * num2  # Esta é uma variável local
    print(var_global)
    
multiply(5, 25)

print(var_global) # observe que ele vai responder que é 10, 
print(var_local) # não temos como saber qual o valor da var local

## Expressão LAMBDA

* Uma expressão Lambda é uma função anônima que você pode usar para criar Delegates ou tipos de árvores de Expressão. São particularmente muito úteis para escrever consultas LINQ. Para facilitar o entendimento, a expressão lambda é uma espécie de função, porém sem nome.

In [ ]:
# Sem o lambda fariamos assim: Definindo uma função
def potencia(num):
    return num**2
potencia(5)

#ou assim
def potencia(num): return num**2
potencia(5)

In [ ]:
# Com o lambda ficaria assim
potencia = lambda num: num**2
potencia(5)

## Erros & Exceções (TRY, EXCEPT, FINALLY)

* Erros de sintaxe, também conhecidos como erros de análise, são talvez o tipo de reclamação mais comum que você recebe enquanto ainda está aprendendo Python.

* TRY: "tente"

* EXCEPT: "exceto"

* FINALLY: "finalmente" força a execução mesmo com erro

In [ ]:
# Utilizando try e except
# pedir para o python dizer se tem erro na operação 8 + s
try:
    8 + 's'
except TypeError:
    print("Operação não permitida")

In [ ]:
def askint():
    try:
        val = int((input("Digite um número: ")))
    except UnboundLocalError:
        print ("Você não digitou um número!")
    finally:
        print ("Obrigado!")
        print (val) 
askint()        

In [ ]:
# Insistindo para o usuário digitar um número com a função "continue"
def askint():
    while True:
        try:
            val = int(input("Digite um número: "))
        except:
            print ("Você não digitou um número!")
            continue # essa função obriga o usuário digitar um numero!
        else:
            print ("Obrigado por digitar um número!")
            break
        finally:
            print("Fim da execução!")
        print (val) 
askint()

##  CLASSES, INSTÂNCIAS E OBJETOS 

* Para criar uma classe, utiliza-se a palavra reservada class. O nome da sua classe segue a mesma convenção de nomes para criação de funções e variáveis, mas normalmente se usa a primeira letra maiúscula em cada palavra no nome da classe.                

* Classes: é como um template, ou seja, um molde. Uma especificação que define o que um objeto desse tipo deverá ter como atributo e como ele deve se comportar.            

* Instâncias: cada instência é um objeto especifico criado a partir de uma classe.                

* Ojbetos: os objetos representam entidades, com suas qualidades (atributos) e ações (métodos) que estas podem realizar.  

* EM PYTHON TUDO É UM OBJETO! (Ex: list, tuple, dict, int, float, ...).

* Função class( ) cria as classes.

* "__init__" é um Construtor chamado para criar um objeto desta classe. 

In [ ]:
# Objetos definidos pelos usuários são criados a partir de instâncias de classes
# Criando uma classe chamada Livro
class Livro():
    
    # Este método vai inicializar cada objeto criado a partir desta classe
    # O nome deste método é __init__
    # (self) é uma referência a cada atributo de um objeto criado a partir desta classe
    def __init__(self, titulo, isbn):
        
        # Atributos de cada objeto criado a partir desta classe. 
        # O self indica que estes são atributos dos objetos
        self.titulo = titulo
        self.isbn = isbn
        print("Construtor chamado para criar um objeto desta classe")
        
    # Métodos são funções, que recebem como parâmetro atributos do objeto criado    
    def imprime(self, titulo, isbn):
        print("Este é o livro %s e ISBN %d" %(titulo, isbn))

In [ ]:
# Criando o objeto Livro2 que é uma instância da classe Livro
Livro2 = Livro("A Menina que Roubava Livros", 77886611)

# Ver atributos
Livro2.titulo

# Método do objeto Livro2
Livro2.imprime("A Menina que Roubava Livros", 77886611)

In [ ]:
# Usamos a função type, para verificar o tipo de um objeto
print(type(10))
print(type(10.3))
print(type([]))
print(type(()))
print(type({}))
print(type('a'))
print(type(Livro2))

In [ ]:
# Criando uma classe
class Funcionarios:
    def __init__(self, nome, salario):
        self.nome = nome
        self.salario = salario

    def listFunc(self):
        print("O nome do funcionário é " + self.nome + " e o salário é R$" + str(self.salario))

In [ ]:
# Criando um objeto chamado Func1 a partir da classe Funcionarios
Func1 = Funcionarios("Obama", 20000)

In [ ]:
# Usando o método da classe
Func1.listFunc()

In [ ]:
# Funções especiais, para visualizar e manipular atributos de um objeto

# hasattr = utilizado para verificar a existencia de um atributo
hasattr(Func1, "salario")

# setattr = utilizado para configurar "set" o atributo "attr"
setattr(Func1, "salario", 4500)

# getattr = utilizado para obter o atributo
getattr(Func1, "salario")

# delattr = utilizado para deletar um objeto
delattr(Func1, "salario")

##  MÉTODOS

* Métodos são funções definidas dentro do corpo de uma classe.
* Os métodos são utilizados para realizar operações com os atributos dos objetos.
* Métodos são usados no conceito de encapsulamento do paradigma de Programação Orientada a Objetos (POO).
* Métodos são basicamente funções definidas dentro de uma classe, para manipular os objetos criados a partir da classe.
* A função def( ) é utilizada para criar métodos, da mesma forma que se cria funções.
* Na análise de dados podemos criar classes para nossas atividades e criar métodos específicos para cada tarefa, encapsulando nossa lógica de programação.

* MÉTODOS ESPECIAIS: ao usar métodos especiais, a classe poderá ter um comportamento semelhante a um dicionário, uma função ou mesmo um número.

In [ ]:
# Criando uma classe chamada Circulo
class Circulo():
    
    # O valor de pi é constante
    pi = 3.14

    # Quando um objeto desta classe for criado, este método será executado e o valor default do raio será 5.
    def __init__(self, raio = 5):
        self.raio = raio 

    # Esse método calcula a área. Self utiliza os atributos deste mesmo objeto
    def area(self):
        return (self.raio * self.raio) * Circulo.pi

    # Método para gerar um novo raio
    def setRaio(self, novo_raio):
        self.raio = novo_raio

    # Método para obter o raio do círculo
    def getRaio(self):
        return self.raio

In [ ]:
# Criando o objeto circ. Uma instância da classe Circulo()
circ = Circulo()

# Executando um método da classe Circulo
circ.getRaio()

In [ ]:
# Criando outro objeto chamado circ1. Uma instância da classe Circulo()
# Agora sobrescrevendo o valor do atributo
circ1 = Circulo(7)

# Executando um método da classe Circulo
circ1.getRaio()

# Imprimindo o raio
print ('O raio é: ', circ.getRaio())

# Imprimindo a area
print('Area igual a: ', circ.area())

In [ ]:
# MÉTODOS ESPECIAIS
# Criando a classe Livro
class Livro():
    def __init__(self, titulo, autor, paginas):
        print ("Livro criado")
        self.titulo = titulo
        self.autor = autor
        self.paginas = paginas
                
    def __str__(self):
        return "Título: %s , autor: %s, páginas: %s " \
    %(self.titulo, self.autor, self.paginas)

    def __len__(self):
        return self.paginas
    
    def len(self):
        return print("Páginas do livro com método comum: ", self.paginas)

In [ ]:
# Atribuindo
livro1 = Livro("Os Lusíadas", "Luis de Camões", 8816)

# Métodos especiais
print(livro1)

# visualizar
str(livro1)
len(livro1)
livro1.len()

# Ao executar a função del para remover um atributo, o Python executa:
# livro1.__delattr__("paginas")
del livro1.paginas

## HERANÇA

* A Classe que deu origem a sub-classe, é chamada super-classe ou classe base.

* Um dos principais benefícios da herança é a reutilização de código e a redução da complexidade dos programas.

* As classes derivadas estendem as funcionalidades das classes base.

In [ ]:
# Criando a classe Animal - Super-classe
class Animal():
    
    def __init__(self):
        print("Animal criado")

    def Identif(self):
        print("Animal")

    def comer(self):
        print("Comendo")

In [ ]:
# Criando a classe Cachorro - Sub-classe
# A subclasse cachorro tem seus proprios métodos mas ela herda alguns métodos
# da super-classe, como por exemplo a classe animal, pois ela é comum entre 
# entre as duas.

class Cachorro(Animal):
    
    def __init__(self):
        Animal.__init__(self) # construtor da classe animal - super-classe.
        print("Objeto Cachorro criado")

    def Identif(self):
        print("Cachorro")

    def latir(self):
        print("Au Au!")

In [ ]:
# Criando um objeto (Instanciando a classe)
rex = Cachorro()

# Executando o método da classe Cachorro (sub-classe)
rex.Identif()

# Executando o método da classe Animal (super-classe)
rex.comer()

# Executando o método da classe Cachorro (sub-classe)
rex.latir()

### **-------------------------------------------------------------------------------------------**
## MÓDULO 4 - Packages e Funções

###  NumPy

https://numpy.org/

* O NumPy, é um acronimo para Numerical Python;                       
* NumPy é um pacote fundamental para computação matemática em python, pois fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos;                    
* O NumPy nasceu a partir de 2 pacotes: Numeric e Numarray;                   
* Esses pacotes foram criados em um esforço para prover uma solução open-source ao Matlab;  
* NumPy não é um pacote para análise de dados, porém ele suporta os objetos do NumPy;           

### O Numpy oferece:
* Um rápido e eficiente array multidimensional;                            
* Ferramentas para leitura de datasets baseados em arrays;                                       
* Operações de álgebra linear;                                      
* Integração com C, C++ e Fortran;                           
* O NumPy adiciona a possibilidade de passar dados de um algoritmo para outro;                       
* O NumPy é mais eficiente para armazenar e manipular dados, em relação a outros objetos Built-in (nativos) em Python, pois ele é ótimizado para performace;


##  Arrays Numpy

* Um Array é um conjunto de valores, todos do mesmo tipo e indexados por uma tupla de valores não-negativos;

OBS:
* Um vetor é um array unidimensional;                
* Uma matriz é um array bidimencionsal;                            
* Um tensor é um array trimensional;                      
* E podemos ter array com mais dimenssões;        

### Por que usar arrays com NumPy?
* Arrays NumPy são homogéneos e possuem tipos estaticos;               
* Arrays NumPy são mais eficientes no uso de memória;                      
* Arrays oferecem rápida implementação de funções matemáticas;                                        
* Arrays são uma opção mais rápida e mais poderosa que listas;  

Embora NumPy não ofereca funcionalidades analíticas de alto nível, a compreensão sobre arrays ajudará a utilizar as ferramentas do Pandas de forma muito mais eficaz, além de ser a base para construção de modelosde Machine Learning em Python.

In [ ]:
# Importando o NumPy
import numpy as np

#### CRIANDO ARRAYS 

In [ ]:
# Criando Array unidimensional também chamado de vetor a partir de uma lista:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(vetor1)
type(vetor1)

In [ ]:
# Imprimindo na tela um elemento específico no array
vetor1[0] 

# Alterando um elemento do array
vetor1[0] = 100

print(vetor1)

In [ ]:
# Não é possível incluir elemento de outro tipo
vetor1[0] = 'Novo elemento'

In [ ]:
# Verificando o formato do array
print(vetor1.shape)
# ele nos diz (9,) ou seja, um vetor unidimensional com 9 observações

#### FUNÇÕES NumPy

In [ ]:
# A função arange cria um vetor contendo uma progressão aritmética 
# a partir de um intervalo - start, stop, step
vetor2 = np.arange(0., 4.5, .5)
print(vetor2)

# Verificando o tipo do objeto
type(vetor2)

# Formato do array
np.shape(vetor2)

# atributo
print (vetor2.dtype)

In [ ]:
# criar um array com zeros
print(np.zeros(10))

In [ ]:
# Retorna 1 nas posições em diagonal e 0 no restante
z = np.eye(3)

# ver
z

In [ ]:
# Os valores passados como parâmetro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))
d

In [ ]:
# Array de números complexos
c = np.array([1+2j, 3+4j, 5+6*1j])
c

In [ ]:
# Array de valores booleanos
b = np.array([True, False, False, True])
b

In [ ]:
# Array de strings
s = np.array(['Python', 'R', 'Julia'])
s

In [ ]:
# O método linspace (linearly spaced vector) retorna um número de 
# valores igualmente distribuídos no intervalo especificado 
np.linspace(0, 10)

In [ ]:
# O método linspace
print(np.linspace(0, 10, 15))

In [ ]:
# Tirando log dos valores
print(np.logspace(0, 5, 10))

#### CRIANDO MATRIZES

In [ ]:
# Criando uma matriz 
matriz = np.array([[1,2,3],[4,5,6]])
matriz

In [ ]:
# ver numero de linhas e colunas
print(matriz.shape)

In [ ]:
# Criando uma matriz 2x3 apenas com números "1"
matriz1 = np.ones((2,3))
matriz1

In [ ]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

# A função matrix cria uma matria a partir de uma sequência
matriz2 = np.matrix(lista)
matriz2

In [ ]:
# Formato da matriz
np.shape(matriz2)

In [ ]:
# Ver tota de observações da matriz
matriz2.size

In [ ]:
# verificar o tamanho do item
matriz2.itemsize

In [ ]:
# verficar o tamnho em mb
matriz2.nbytes

In [ ]:
# verificar dimenssões
matriz2.ndim

In [ ]:
# Alterando um elemento da matriz
matriz2[1,0] = 100

In [ ]:
# ver tipo de dados em cada linha
x = np.array([1, 2])  # NumPy decide o tipo dos dados
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dados
z = np.array([1, 2], dtype=np.float64)  # Forçamos um tipo de dado em particular

print (x.dtype, y.dtype, z.dtype)

In [ ]:
# criar matriz com tipo float
matriz3 = np.array([[24, 76], [35, 89]], dtype=float)
matriz3

#### USANDO O MÉTODO random() NumPy

In [ ]:
# Gerar 10 valores aleatórios
print(np.random.rand(10))

#### OPERAÇÕES COM DATASETS

In [25]:
# Carregando um dataset para dentro de um array sem cabeçalio
arquivo = np.loadtxt("D:/onedrive/Documentos/ANALISE_DADOS/SOFTWARE_PYTHON/Arquivos_utilizados/iris.csv", delimiter=',', usecols=(0,1,2,3), skiprows=1)
print (arquivo)
type(arquivo)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

numpy.ndarray

#### ESTATÍSTICAS 

In [ ]:
# Criando um array
A = np.array([15, 23, 63, 94, 75])

In [ ]:
# Em estatística a média
np.mean(A)

In [ ]:
# desvio padrão
np.std(A)

In [ ]:
# Variância
np.var(A)

In [ ]:
# Gerar vetor
d = np.arange(1, 10)

In [ ]:
# Retorna o produto dos elementos
np.prod(d)

In [ ]:
# Soma acumulada dos elementos
np.cumsum(d)

In [ ]:
# Gerar vetor de forma aleatória
a = np.random.randn(10,2)
a

#### OUTRAS OPERAÇÕES COM ARRAYS

In [ ]:
# criar um array com diagona 1 2 e 3
a = np.diag(np.arange(3))
a

In [ ]:
# Slicing da linha 1 e coluna 1 (lembrese o python começa em 0)
a[1, 1]

In [ ]:
# Slicing da linha 1
a[1]

In [ ]:
# Criar outro arrary
b = np.arange(10)
b

In [ ]:
# [start:end:step] pedindo os elementos que começa na posição 2 até 9 
#pulando de 3 em 3
b[2:9:3] 

In [ ]:
# Comparação
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

In [ ]:
# Comparar os dois arrays
np.array_equal(a, b)

In [ ]:
# pedir valores min e max
a.min()
a.max()

In [ ]:
# Usando o método around
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
b

In [ ]:
# Copiando um array
C = b.flatten()
C

In [ ]:
# Somando um elemento ao array
D = np.array(C) + 1.5
D

In [ ]:
# Repetindo os elementos de um array
np.repeat(D, 3)

In [ ]:
# Repetindo as linhas 
np.tile(D, 3)

In [ ]:
# Concatenando
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5 ,6])
np.concatenate((a1, a2), axis=0)

### **-------------------------------------------------------------------------------------------**
##   MÓDULO 5 - Carregar Arquivos ou Dados e Exportar

In [26]:
# Como carregar dados em CSV com pandas
df = pd.read_csv('df.csv', sep = ",")

FileNotFoundError: [Errno 2] No such file or directory: 'df.csv'

In [27]:
# Como salvar dados em CSV com pandas
df.to_csv('df.csv', encoding = 'utf-8', index = False)

NameError: name 'df' is not defined

In [28]:
# Abrir arquivo TXT no modo leitura "r" de read
arquivo_txt_r = open("arquivo1.txt", "r", encoding='utf8')

# Abrir arquivo TXT no modo escrita "w" de write
arquivo_txt_w = open("arquivo.txt", "w", encoding='utf8')

# Gravando arquivo
arquivo_txt_w.write("Testando gravação de arquivos em Python")

# Abrir arquivo TXT no modo acrescentar "a" de append
arquivo_txt_a = open("arquivo.txt", "a", encoding='utf8')

# Acrescentando conteúdo
arq2.write(" Acrescentando conteúdo")

# Fechar arquivo 
arquivo_txt.close()


FileNotFoundError: [Errno 2] No such file or directory: 'arquivo1.txt'

### **-------------------------------------------------------------------------------------------**
##  MÓDULO 6 - Visualizar e Análise Exploratória de Dados

In [ ]:
# Ver o tipo da variável
type() # podendo ser int ex:5; float ex:5.2; string ex:"teste"

In [ ]:
import pandas as pd
d = {'col1': [1, 2, 5, 5.2, 17, 83, 93, 100], 
     'col2': [3, 4, 3.3, 2, 15, 95, 32, 200]}
df = pd.DataFrame(data=d)
df

In [ ]:
# ver as primeiras linhas de um data.frame
df.head()

In [ ]:
# ver todo data.frame
df

In [ ]:
# ver todos os dataframes carregados
%who
%who_ls

In [ ]:
# Ver quantidade de linhas e colunas de um data.frame
df.shape

In [ ]:
# ver outras informações como tipo de variável observaçoes numero das colunas
df.info()

In [ ]:
# ver o total de missings das colunas
df.isnull().sum()

In [ ]:
# table(R) ou tab(stata) no python
df.value_counts()

# table ampliado para todas as variáveis
df.groupby(['col1']).count()

In [ ]:
# Estatisticas descritivas
summary = df.describe()
summary.head()

#se preferir pode transpor e deixar as variáveis nas linhas
summary = summary.transpose()
summary.head()

In [ ]:
# Matriz de correlção
corr = df.corr()
corr.head()

In [ ]:
# Contar o número de caracteres metodo "tell" que significa contar
arquivo=[]
print(arquivo.tell())

In [ ]:
# visualizando datas com datetime
import datetime

# ver data hora atual
agora = datetime.datetime.now()
print(agora)

In [ ]:
# Olhando hora minuto segundo milisegundo
import datetime
t = datetime.time(7, 43, 28)
print (t)
print ('Hora  :', t.hour)
print ('Minute:', t.minute)
print ('Segundo:', t.second)
print ('Microsegundo:', t.microsecond)

In [ ]:
# ver data hora atual
import datetime
hoje = datetime.date.today()
print (hoje)
print ('ctime:', hoje.ctime())
print ('Ano:', hoje.year)
print ('Mês :', hoje.month)
print ('Dia :', hoje.day)

### **-------------------------------------------------------------------------------------------**
##   MÓDULO 7 - Manipulação de Dados 

In [ ]:
# O operadoções em Python
1 + 1  # soma
4 - 3  # Subtração
3 * 3  # Multiplicação
3 / 2  # Divisão
4 // 3 # Divisão inteira, sem considerar o resto
4 ** 2 # Potência
pow(4,2) # Potência
10 % 3 # Módulo
abs(-8) # Retorna o valor absoluto
round(3.14151922, 2) # Retorna o valor com arredondamento de duas casas
6 > 3 # sinal de maior
4 < 8 # sinal de menor
4 >= 4 # maior ou igual
4 <= 4 # menor ou igual
=  # é um sinal de atribuição
== # é igual
20 % 6 # Resto da divisão
and # "e" lógico
or # "ou" lógico
not # "não" lógico
+= # adiciona o item a mais e soma (utilizado em estrutura de repetição)
bool(0) # numero booleano onde 0 = false
bool(1) # numero booleano onde 0 = true
math.sqrt(25) # Raiz quadrada Usando um dos métodos do módulo math (import math) 

In [ ]:
# Imputar dados com a moda mediana e média
# Para moda "obs [0] significa que vamos pegar o valor que mais se repete"
df['var'].fillna(df['var'].mode()[0], inplace = True) 
df['var'].fillna(df['var'].median(), inplace = True) 
df['var'].fillna(df['var'].mean(), inplace = True) 

In [ ]:
# Remover duplicados
df =df.drop_duplicates()

In [ ]:
# Usando a função list() para converter uma tupla para lista
lista_t2 = list(t2)

In [ ]:
# Usando a função tuple() para converter uma lista para tupla
t2 = tuple(lista_t2)

In [ ]:
# valor máximo da lista Função max()
max(lista)

In [ ]:
# valor mínimo da lista Função min()
min(lista)

In [ ]:
# Fazendo split dos dados
def split_string(text):
    return text.split(" ")
texto = "Esta função será bastante útil para separar grandes volumes de dados."

# Isso divide a string em uma lista.
print(split_string(texto))

# Podemos atribuir o output de uma função, para uma variável
token = split_string(texto)
token

In [ ]:
# Como fazer um sorteio aleatório
import random
random.choice(['Maça', 'Banana', 'Laranja'])

In [ ]:
# Escolher 10 valores aleatoriamente entre 0 e 100
random.sample(range(100), 10)

In [ ]:
# Manipulando datas com datetime
import datetime

# Data 1 2015-04-28
d1 = datetime.date(2015, 4, 28)
print ('d1:', d1)

# Data 2 2016-04-28
d2 = datetime.date(2016, 4, 28)
print ('d2:', d2)

# Diferença em dias entre duas datas
d2 - d1

### **-------------------------------------------------------------------------------------------**
##   MÓDULO 8 - SQL com Python utilizando SQLite 

In [ ]:
# Adicionar uma imagen do pc no jupyter notebook
from IPython.display import Image
Image(filename='Imagens_utilizadas/imagem sqlite.jpg',width=1200, height=300)

## SQLite 

* O SQLite é instalado automaticamente juntocom o Anaconda.
* Documentação SQLite: http://www.sqlite.org/docs.html 
* É possivel abrir o SQLite no SQL Browser https://sqlitebrowser.org/dl/

#### Bancos de dados Relacionais
* Bancos de dados relacionais como MySQL, PostgreSQL e SQLite3 representam e armazenam dados em tabelas e linhas.
* Os bancos de dados relacionais utilizam SQL (Structured Querying Language), sendo uma escolha adequada para aplicativos que envolvam o gerenciamento de várias transações.
* A estrutura de um banco de dados relacional permite vincular informações de diferentes tabelas por meio do uso de chaves (ou índices).

### Exemplo 1 - Como criar um banco SQL e adicionar valores.

In [ ]:
# Reemover banco de dados SQLite (caso exista)
import os
os.remove("escola.db") if os.path.exists("escola.db") else None

In [ ]:
# Importando o módulo de acesso ao SQLite
import sqlite3

In [ ]:
# Cria uma conexão com o banco de dados. 
# Se o banco de dados não existir, ele é criado neste momento.
con = sqlite3.connect('escola.db')
type(con)

In [ ]:
# Criando um cursor 
# (Um cursor permite percorrer todos os registros em um conjunto de dados)
cur = con.cursor()
type(cur)

In [ ]:
# Cria uma instrução sql
# OBS: a contra barra \ serve para quebrar o comando em mais de uma linha
sql_create = 'create table cursos '\
             '(id integer primary key, '\
             'titulo varchar(100), '\
             'categoria varchar(140))'

# Executando a instrução sql no cursor
cur.execute(sql_create)

# Criando outra sentença SQL para inserir registros
sql_insert = 'insert into cursos values (?, ?, ?)'

# Dados
recset = [(1000, 'Ciência de Dados', 'Data Science'),
          (1001, 'Big Data Fundamentos', 'Big Data'),
          (1002, 'Python Fundamentos', 'Análise de Dados')]

# Inserindo os registros
for rec in recset:
    cur.execute(sql_insert, rec)
    
# Grava a transação
con.commit()

In [ ]:
# Criando outra sentença SQL para selecionar registros
sql_select = 'select * from cursos'

In [ ]:
# Seleciona todos os registros e recupera os registros
cur.execute(sql_select)

# OBS: o fetchall pega todos os registros e salva em dados
dados = cur.fetchall()

In [ ]:
# Mostra dados linha a linha
for linha in dados:
    print ('Curso Id: %d, Título: %s, Categoria: %s \n' % linha)

In [ ]:
# Mostrar dados 
print(dados)

In [ ]:
# Gerando outros registros
recset = [(1003, 'Gestão de Dados com MongoDB', 'Big Data'),
          (1004, 'R Fundamentos', 'Análise de Dados')]

# Inserindo os registros
for rec in recset:
    cur.execute(sql_insert, rec)
    
# Gravando a transação
con.commit()

In [ ]:
# Seleciona todos os registros
cur.execute('select * from cursos')

# Recupera os resultados
recset = cur.fetchall()

# Mostra
for rec in recset:
    print ('Curso Id: %d, Título: %s, Categoria: %s \n' % rec)

In [ ]:
# Fecha a conexão
con.close()

### Exemplo 2 - Automatizando comandos SQL

* A vantagem de automatizar os comandos é não precisar ficar repetindo comandos SQL a todos momento.

### Automatizar os comandos CREATE e INSERT

In [ ]:
# Remove o arquivo com o banco de dados SQLite (caso exista)
import os
os.remove("dsa.db") if os.path.exists("dsa.db") else None

In [ ]:
import sqlite3
 
# Criando uma conexão
conn = sqlite3.connect('dsa.db')   

# Criando um cursor
c = conn.cursor()
 
# Função para criar uma tabela
def create_table():
    c.execute('CREATE TABLE IF NOT EXISTS produtos(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, date TEXT, '\
              'prod_name TEXT, valor REAL)')
    
# Função para inserir uma linha
def data_insert():
    c.execute("INSERT INTO produtos VALUES(10, '2020-05-02 14:32:11', 'Teclado', 90 )")
    conn.commit()
    c.close()
    conn.close()

In [ ]:
# Criar tabela
create_table()

In [ ]:
# Inserir dados
data_insert()

In [ ]:
# Encerrando a conexão
conn.close()

### [CONTINUAÇÃO] - Abrindo base gerada e adcionando dados automaticamente                  

In [ ]:
# importar biblioteca
import sqlite3
import random
import time
import datetime
 
# conectando novamente no banco gerado
conn = sqlite3.connect('dsa.db')   

# Criando um cursor
c = conn.cursor()
  
# Usando variáveis para inserir dados    
def data_insert_var():
    new_date = datetime.datetime.now()
    new_prod_name = 'Monitor'
    new_valor = random.randrange(50,100)
    c.execute("INSERT INTO produtos (date, prod_name, valor) VALUES (?, ?, ?)", (new_date, new_prod_name, new_valor))
    conn.commit()

In [ ]:
# Gerando valores e inserindo na tabela
for i in range(10):
    data_insert_var()
    time.sleep(1)

In [ ]:
# Encerrando a conexão
c.close()
conn.close()

### [CONTINUAÇÃO] -  Automatizando o comando SELECT 

In [ ]:
import sqlite3
import random
import time
import datetime
 
# Criando uma conexão
conn = sqlite3.connect('dsa.db')   

# Criando um cursor
c = conn.cursor()
  
# Leitura de dados
def leitura_todos_dados():
    c.execute("SELECT * FROM PRODUTOS")
    for linha in c.fetchall():
        print(linha)
        
# Leitura de registros específicos
def leitura_registros():
    c.execute("SELECT * FROM PRODUTOS WHERE valor > 60.0")
    for linha in c.fetchall():
        print(linha)      
        
# Leitura de colunas específicos
def leitura_colunas():
    c.execute("SELECT * FROM PRODUTOS")
    for linha in c.fetchall():
        print(linha[3])         


In [ ]:
# Select nos dados
leitura_todos_dados()

In [ ]:
# Leitura de registros específicos
leitura_registros()

In [ ]:
# Leitura de colunas específicas
leitura_colunas()

In [ ]:
# Encerrando a conexão
c.close()
conn.close()

### [CONTINUAÇÃO] - Automatizando os comandos UPDATE e DELETE

In [ ]:
import sqlite3
import random
import time
import datetime
 
# Criando uma conexão
conn = sqlite3.connect('dsa.db')   

# Criando um cursor
c = conn.cursor()
        
# Update
def atualiza_dados():
    c.execute("UPDATE produtos SET valor = 70.00 WHERE valor = 98.0")
    conn.commit()
    
# Delete
def remove_dados():
    c.execute("DELETE FROM produtos WHERE valor = 62.0")
    conn.commit()

In [ ]:
atualiza_dados()

In [ ]:
leitura_todos_dados()

In [ ]:
remove_dados()

In [ ]:
leitura_todos_dados()

### [CONTINUAÇÃO] - Plotando graficos apartir de dados do SQL

In [ ]:
# Instala a versão exata do pacote matplotlib
!pip install -q -U matplotlib==3.2.1

In [ ]:
import matplotlib as mat
mat.__version__

In [ ]:
import sqlite3
import random
import datetime
import matplotlib.pyplot as plt
%matplotlib notebook
 
# Criando uma conexão
conn = sqlite3.connect('dsa.db')   

# Criando um cursor
c = conn.cursor()

In [ ]:
# Gerar gráfico com os dados no banco de dados
def dados_grafico():
    c.execute("SELECT id, valor FROM produtos")
    ids = []
    valores = []
    dados = c.fetchall()
    for linha in dados:
        ids.append(linha[0])
        valores.append(linha[1])
        
    plt.bar(ids, valores)
    plt.show()

In [ ]:
# Gerando gráficos
dados_grafico()

### **-------------------------------------------------------------------------------------------**
##  MÓDULO 9 - Stata 16 e 17 em Python

In [ ]:
# Adicionar uma imagen do pc no jupyter notebook
from IPython.display import Image
Image(filename='Imagens_utilizadas/imagem stata17.jpg',width=1000, height=300)

##  Stata

* Para utilizar este módulo é preciso ter o stata 16 ou superior instalado
* Documentação PyStata: https://blog.stata.com/2020/08/18/stata-python-integration-part-1-setting-up-stata-to-use-python/ 
* Chamando Stata com Jupyter notebook: https://www.youtube.com/watch?v=VGRDR3J346M

#### Utilizando Stata em Python
* Para começar, precisamos configurar o pacote pystata dentro do Python para que ele possa ser encontrado e importado pelo Python.

In [ ]:
import os
os.chdir('C:/Program Files (x86)/Stata17/utilities')
from pystata import config
config.init('mp')

In [ ]:
%%stata
sysyse auto, clear
summary

### **-------------------------------------------------------------------------------------------**
##  MÓDULO 10 - TensorFlow

##  TensorFlow

https://www.tensorflow.org/?hl=pt-br



In [ ]:
# Instalando TensorFlow
!pip3 install tensorflow

In [ ]:
# ver a versão instalada
import tensorflow as tf
tf.__version__

O Tensorflow é uma das bibliotecas mais amplamente utilizadas para implementar o aprendizado de máquina e outros algoritmos que envolvem grandes operações matemáticas. O Tensorflow foi desenvolvido pelo Google e é uma das bibliotecas de aprendizado de máquina mais populares no GitHub. O Google usa o Tensorflow para aprendizado de máquina em quase todos os aplicativos. Se você já usou o Google Photos ou o Google Voice Search, então já utlizou uma aplicação criada com a ajuda do TensorFlow. Vamos compreender os detalhes por trás do TensorFlow.

Matematicamente, um tensor é um vetor N-dimensional, significando que um tensor pode ser usado para representar conjuntos de dados N-dimensionais. Aqui está um exemplo:

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/tensor1.png')

A figura acima mostra alguns tensores simplificados com dimensões mínimas. À medida que a dimensão continua crescendo, os dados se tornam mais e mais complexos. Por exemplo, se pegarmos um Tensor da forma (3x3), posso chamá-lo de matriz de 3 linhas e colunas. Se eu selecionar outro Tensor de forma (1000x3x3), posso chamá-lo como tensor ou conjunto de 1000 matrizes 3x3. Aqui chamamos (1000x3x3) como a forma ou dimensão do tensor resultante. Os tensores podem ser constantes ou variáveis.

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/tensor2.png')

### TensorFlow x NumPy

TensorFlow e NumPy são bastante semelhantes (ambos são bibliotecas de matriz N-d). NumPy é o pacote fundamental para computação científica com Python. Ele contém um poderoso objeto array N-dimensional, funções sofisticadas (broadcasting) e etc. Acredito que os usuários Python não podem viver sem o NumPy. O NumPy tem suporte a matriz N-d, mas não oferece métodos para criar funções de tensor e automaticamente computar derivadas, além de não ter suporte a GPU, e esta é uma das principais razões para a existência do TensorFlow. Abaixo uma comparação entre NumPy e TensorFlow, e você vai perceber que muitas palavras-chave são semelhantes.

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/tf_numpy.png')

## Grafo Computacional

Conheça a Formação Inteligência Artificial, um programa completo, 100% online e 100% em português, com mais de 402 horas em 9 cursos de nível intermediário/avançado, que vão ajudá-lo a se tornar um dos profissionais mais cobiçados do mercado de tecnologia. Clique no link abaixo, faça sua inscrição, comece hoje mesmo e aumente sua empregabilidade:

https://www.datascienceacademy.com.br/bundle/formacao-inteligencia-artificial

Agora sabemos o que o tensor realmente significa e é hora de entender o fluxo. Este fluxo refere-se a um grafo computacional ou simplesmente um grafo. 

Grafos computacionais são uma boa maneira de pensar em expressões matemáticas. O conceito de grafo foi introduzido por Leonhard Euler em 1736 para tentar resolver o problema das Pontes de Konigsberg. Grafos são modelos matemáticos para resolver problemas práticos do dia a dia, com várias aplicações no mundo real tais como: circuitos elétricos, redes de distribuição, relações de parentesco entre pessoas, análise de redes sociais, logística, redes de estradas, redes de computadores e muito mais. Grafos são muito usados para modelar problemas em computação.

Um Grafo é um modelo matemático que representa relações entre objetos. Um grafo G = (V, E) consiste de um conjunto de vértices V (também chamados de nós), ligados por um conjunto de bordas ou arestas E. 

Considere o diagrama abaixo:

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/grafo1.png')

Existem três operações: duas adições e uma multiplicação. Ou seja: 

- c = a+b
- d = b+1
- e = c∗d

Para criar um grafo computacional, fazemos cada uma dessas operações nos nós, juntamente com as variáveis de entrada. Quando o valor de um nó é a entrada para outro nó, uma seta vai de um para outro e temos nesse caso um grafo direcionado.

Esses tipos de grafos surgem o tempo todo em Ciência da Computação, especialmente ao falar sobre programas funcionais. Eles estão intimamente relacionados com as noções de grafos de dependência e grafos de chamadas. Eles também são a principal abstração por trás do popular framework de Deep Learning, o TensorFlow.

Para mais detalhes sobre grafos, leia um dos capítulos do Deep Learning Book:

https://deeplearningbook.com.br/algoritmo-backpropagation-parte1-grafos-computacionais-e-chain-rule/

Um grafo para execução de um modelo de Machine Learning pode ser bem grande e podemos executar sub-grafos (porções dos grafos) em dispositivos diferentes, como uma GPU. Exemplo:

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/grafo2.png')

A figura acima explica a execução paralela de sub-grafos. Aqui estão 2 operações de multiplicação de matrizes, já que ambas estão no mesmo nível. Os nós são executados em gpu_0 e gpu_1 em paralelo.

### Modelo de Programação TensorFlow

O principal objetivo de um programa TensorFlow é expressar uma computação numérica como um grafo direcionado. A figura abaixo é um exemplo de grafo de computação, que representa o cálculo de h = ReLU (Wx + b). Este é um componente muito clássico em muitas redes neurais, que conduz a transformação linear dos dados de entrada e, em seguida, alimenta uma linearidade (função de ativação linear retificada, neste caso).

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/grafo3.png')

O grafo acima representa um cálculo de fluxo de dados; cada nó está em operação com zero ou mais entradas e zero ou mais saídas. As arestas do grafo são tensores que fluem entre os nós. Os Cientistas de Dados geralmente constroem um grafo computacional usando uma das linguagens frontend suportadas como Python e C ++ e, em seguida, iniciam o grafo.

Vamos ver o grafo computacional acima em detalhes. Truncamos o grafo e deixamos a parte acima do nó ReLU, que é exatamente o cálculo h = ReLU (Wx + b).

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/grafo4.png')

Podemos ver o grafo como um sistema, que tem entradas (os dados x), saída (h neste caso), variáveis com estado (W e b) e um monte de operações (matmul, add e ReLU). Deixe-me apresentar-lhe um por um.

- Variáveis: quando treinamos um modelo, usamos variáveis para manter e atualizar parâmetros. Ao contrário de muitos tensores que fluem ao longo das margens do grafo, uma variável é um tipo especial de operação. Na maioria dos modelos de aprendizado de máquina, existem muitos parâmetros que temos que aprender, que são atualizados durante o treinamento. Variáveis são nós com estado que armazenam parâmetros e produzem seus valores atuais de tempos em tempos. Seus estados são mantidos em múltiplas execuções de um grafo. Por exemplo, os valores desses nós não serão atualizados até que uma etapa completa de treinamento usando um mini lote de dados seja concluída.


- Operações matemáticas: Neste grafo, existem três tipos de operações matemáticas. A operação MatMul multiplica dois valores de matriz; A operação Add adiciona elementos e a operação ReLU é ativada com a função linear retificada de elementos.

### Hello World

In [ ]:
# Cria um tensor
# Esse tensor é adicionado como um nó ao grafo.
hello = tf.constant('Hello, TensorFlow!')
print(hello)

### Operações Matemáticas com Tensores

#### Soma

In [ ]:
# Constantes
const_a = tf.constant(5)
const_b = tf.constant(9)

In [ ]:
print(const_a)

In [ ]:
# Soma
total = const_a + const_b
print(total)

In [ ]:
# Criando os nodes no grafo computacional
node1 = tf.constant(5, dtype = tf.int32)
node2 = tf.constant(9, dtype = tf.int32)
node3 = tf.add(node1, node2)
 
# Executa o grafo
print("\nA soma do node1 com o node2 é:", node3)

#### Subtração

In [ ]:
# Tensores randômicos
rand_a = tf.random.normal([3], 2.0)
rand_b = tf.random.uniform([3], 1.0, 4.0)

In [ ]:
print(rand_a)

In [ ]:
print(rand_b)

In [ ]:
# Subtração
diff = tf.subtract(rand_a, rand_b)

In [ ]:
type(diff)

In [ ]:
print('\nSubtração entre os 2 tensores é: ', diff)

#### Divisão

In [ ]:
# Tensores
node1 = tf.constant(21, dtype = tf.int32)
node2 = tf.constant(7, dtype = tf.int32)

In [ ]:
# Divisão
div = tf.math.truediv(node1, node2)

In [ ]:
print('\nDivisão Entre os Tensores: \n', div)

#### Multiplicação

Para aprender a teoria e prática sobre operações com matrizes acesse <a href="https://www.datascienceacademy.com.br/bundle/formacao-inteligencia-artificial">aqui</a>.

In [ ]:
# Criando tensores
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.],[7.]])

In [ ]:
print(tensor_a)

In [ ]:
print(tensor_b)

In [ ]:
# Multiplicação
# tf.math.multiply(X, Y) executa multiplicação element-wise 
# https://www.tensorflow.org/api_docs/python/tf/math/multiply
prod = tf.math.multiply(tensor_a, tensor_b)

In [ ]:
print('\nProduto Element-wise Entre os Tensores: \n', prod)

In [ ]:
# Outro exemplo de Multiplicação de Matrizes
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])

In [ ]:
print(mat_a)

In [ ]:
print(mat_b)

In [ ]:
# Multiplicação
# tf.linalg.matmul(X, Y) executa multiplicação entre matrizes 
# https://www.tensorflow.org/api_docs/python/tf/linalg/matmul
mat_prod = tf.linalg.matmul(mat_a, mat_b)

In [ ]:
print('\nProduto Element-wise Entre os Tensores (Matrizes): \n', mat_prod)

In [ ]:
from IPython.display import Image
Image('Arquivos_utilizados/matrizes.png')

### Usando Variáveis

O TensorFlow também possui nodes variáveis que podem conter dados variáveis. Elas são usados principalmente para manter e atualizar parâmetros de um modelo de treinamento.

Variáveis são buffers na memória contendo tensores. Elas devem ser inicializados e podem ser salvas durante e após o treinamento. Você pode restaurar os valores salvos posteriormente para exercitar ou analisar o modelo.

Uma diferença importante a notar entre uma constante e uma variável é:

O valor de uma constante é armazenado no grafo e seu valor é replicado onde o grafo é carregado. Uma variável é armazenada separadamente e pode estar em um servidor de parâmetros.

In [ ]:
# Criado o mesmo tensor com tf.Variable() e tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

In [ ]:
# Isso vai gerar erro - requer o método assign()
changeable_tensor[0] = 7
changeable_tensor

In [ ]:
# Isso vai funcionar
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Isso vai gerar erro (não podemos alterar tensores criados com tf.constant())
unchangeable_tensor[0].assign(7)
unchangleable_tensor

Qual você deve usar? `tf.constant ()` ou `tf.Variable ()`?

Dependerá do que o seu problema requer. No entanto, na maioria das vezes, o TensorFlow escolhe automaticamente para você (ao carregar dados ou modelar dados).

### Outras Formas de Criar Tensores

In [ ]:
# Tensor preenchido com 1
tf.ones(shape=(3, 2))

In [ ]:
# Tensor preenchido com 0
tf.zeros(shape=(3, 2))

In [ ]:
# Cria um tensor rank 4 (4 dimensões)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

In [ ]:
# Imprime atributos do tensor
print("Tipo de dado de cada elemento:", rank_4_tensor.dtype)
print("Número de dimensões (rank):", rank_4_tensor.ndim)
print("Shape do tensor:", rank_4_tensor.shape)
print("Elementos no eixo 0 do tensor:", rank_4_tensor.shape[0])
print("Elementos no último eixo do tensor:", rank_4_tensor.shape[-1])
print("Número total de elementos (2*3*4*5):", tf.size(rank_4_tensor).numpy())

In [ ]:
# Obtém os 2 primeiros itens de cada dimensão
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Obtém a dimensão de cada índice, exceto o final
rank_4_tensor[:1, :1, :1, :]

In [ ]:
# Cria um tensor e rank 2 (2 dimensões)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

In [ ]:
# Obtém o último item de cada linha
rank_2_tensor[:, -1]